version: '3.3'
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'casita'
      MYSQL_PASSWORD: 'saluzzo'
      MYSQL_ROOT_PASSWORD: 'saluzzo'
    ports:
      - '3306:3306'
